name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build moments (FreeBSD only)

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
        check-latest: true

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Build Frontend
      run: |
        cd front
        pnpm i --frozen-lockfile
        pnpm build
        mkdir -p ../backend/router/frontend
        rm -rf ../backend/router/frontend/dist
        cp -R dist ../backend/router/frontend/dist
        cd ..

    - name: Build FreeBSD binary
      run: |
        cd backend
        mkdir -p artifact

        GOOS=freebsd GOARCH=amd64 CGO_ENABLED=0 go build -o moments ./cmd/moments/main.go

        cp moments artifact/moments
        cd artifact
        tar -czvf ../moments-freebsd-amd64.tar.gz *
        cd ..
        cd ..

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: moments-freebsd
        path: backend/moments-freebsd-amd64.tar.gz

    - name: Generate release tag
      id: tag
      run: |
        RELEASE_TAG=$(date +"v%Y.%m.%d-%H%M")
        echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: backend/moments-freebsd-amd64.tar.gz

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 8